---
repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--exclude ./exps]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: debug-statements
      language_version: python3

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    - id: pyupgrade

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--skip __init__.py]

  # https://github.com/pre-commit/pre-commit/issues/761#issuecomment-394167542
  -   repo: local
      hooks:
      -   id: pytest
          name: pytest
          entry: bash -c "pytest ./tests"
          language: system
          type: [python]
          pass_filenames: false
          always_run: true
